/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ankle_functions_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {1, 1, 1};
static const casadi_int casadi_s1[3] = {2, 2, 1};

/* ankle_inv:(pitch,roll,D,h1,h2,r,u_x,u_z)->(phi_l,phi_r) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15;
  a00=arg[0]? arg[0][0] : 0;
  a01=cos(a00);
  a02=arg[6]? arg[6][0] : 0;
  a03=(a01*a02);
  a04=sin(a00);
  a05=arg[1]? arg[1][0] : 0;
  a06=sin(a05);
  a07=(a04*a06);
  a08=arg[2]? arg[2][0] : 0;
  a09=2.;
  a08=(a08/a09);
  a07=(a07*a08);
  a03=(a03+a07);
  a07=cos(a05);
  a10=(a04*a07);
  a11=arg[7]? arg[7][0] : 0;
  a10=(a10*a11);
  a03=(a03+a10);
  a10=(-a03);
  a12=arg[3]? arg[3][0] : 0;
  a13=(a01*a06);
  a13=(a13*a08);
  a04=(a04*a02);
  a13=(a13-a04);
  a01=(a01*a07);
  a01=(a01*a11);
  a13=(a13+a01);
  a13=(a12-a13);
  a10=atan2(a10,a13);
  a03=casadi_sq(a03);
  a13=casadi_sq(a13);
  a03=(a03+a13);
  a13=arg[5]? arg[5][0] : 0;
  a01=casadi_sq(a13);
  a01=(a03+a01);
  a12=casadi_sq(a12);
  a07=(a07*a08);
  a06=(a06*a11);
  a07=(a07-a06);
  a07=(a08-a07);
  a07=casadi_sq(a07);
  a12=(a12-a07);
  a01=(a01-a12);
  a12=(a09*a13);
  a03=sqrt(a03);
  a12=(a12*a03);
  a01=(a01/a12);
  a12=1.;
  a01=casadi_fmin(a01,a12);
  a03=-1.;
  a01=casadi_fmax(a01,a03);
  a01=acos(a01);
  a10=(a10+a01);
  a01=1.5707963267948966e+00;
  a10=(a10-a01);
  if (res[0]!=0) res[0][0]=a10;
  a10=cos(a00);
  a07=(a10*a02);
  a00=sin(a00);
  a06=sin(a05);
  a04=(a00*a06);
  a04=(a04*a08);
  a07=(a07-a04);
  a05=cos(a05);
  a04=(a00*a05);
  a04=(a04*a11);
  a07=(a07+a04);
  a04=(-a07);
  a14=arg[4]? arg[4][0] : 0;
  a15=(a10*a05);
  a15=(a15*a11);
  a00=(a00*a02);
  a10=(a10*a06);
  a10=(a10*a08);
  a00=(a00+a10);
  a15=(a15-a00);
  a15=(a14-a15);
  a04=atan2(a04,a15);
  a07=casadi_sq(a07);
  a15=casadi_sq(a15);
  a07=(a07+a15);
  a15=casadi_sq(a13);
  a15=(a07+a15);
  a14=casadi_sq(a14);
  a05=(a05*a08);
  a06=(a06*a11);
  a05=(a05+a06);
  a05=(a05-a08);
  a05=casadi_sq(a05);
  a14=(a14-a05);
  a15=(a15-a14);
  a09=(a09*a13);
  a07=sqrt(a07);
  a09=(a09*a07);
  a15=(a15/a09);
  a15=casadi_fmin(a15,a12);
  a15=casadi_fmax(a15,a03);
  a15=acos(a15);
  a04=(a04+a15);
  a04=(a04-a01);
  if (res[1]!=0) res[1][0]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int ankle_inv(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ankle_inv_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ankle_inv_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ankle_inv_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ankle_inv_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ankle_inv_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ankle_inv_incref(void) {
}

CASADI_SYMBOL_EXPORT void ankle_inv_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ankle_inv_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int ankle_inv_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real ankle_inv_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ankle_inv_name_in(casadi_int i) {
  switch (i) {
    case 0: return "pitch";
    case 1: return "roll";
    case 2: return "D";
    case 3: return "h1";
    case 4: return "h2";
    case 5: return "r";
    case 6: return "u_x";
    case 7: return "u_z";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ankle_inv_name_out(casadi_int i) {
  switch (i) {
    case 0: return "phi_l";
    case 1: return "phi_r";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ankle_inv_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ankle_inv_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ankle_inv_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ankle_inv_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* ankle_jacobian:(pitch,roll,D,h1,h2,r,u_x,u_z)->(J[2x2]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  a00=arg[0]? arg[0][0] : 0;
  a01=cos(a00);
  a02=arg[6]? arg[6][0] : 0;
  a03=(a01*a02);
  a04=sin(a00);
  a05=arg[1]? arg[1][0] : 0;
  a06=sin(a05);
  a07=(a04*a06);
  a08=arg[2]? arg[2][0] : 0;
  a09=2.;
  a08=(a08/a09);
  a07=(a07*a08);
  a03=(a03+a07);
  a07=cos(a05);
  a10=(a04*a07);
  a11=arg[7]? arg[7][0] : 0;
  a10=(a10*a11);
  a03=(a03+a10);
  a10=casadi_sq(a03);
  a12=arg[3]? arg[3][0] : 0;
  a13=(a01*a06);
  a13=(a13*a08);
  a14=(a04*a02);
  a13=(a13-a14);
  a14=(a01*a07);
  a14=(a14*a11);
  a13=(a13+a14);
  a13=(a12-a13);
  a14=casadi_sq(a13);
  a10=(a10+a14);
  a14=(a03/a10);
  a15=sin(a00);
  a16=(a06*a15);
  a16=(a08*a16);
  a17=cos(a00);
  a18=(a02*a17);
  a16=(a16+a18);
  a18=(a07*a15);
  a18=(a11*a18);
  a16=(a16+a18);
  a18=(a14*a16);
  a10=(a13/a10);
  a19=(a06*a17);
  a19=(a08*a19);
  a15=(a02*a15);
  a19=(a19-a15);
  a17=(a07*a17);
  a17=(a11*a17);
  a19=(a19+a17);
  a17=(a10*a19);
  a18=(a18-a17);
  a17=-1.;
  a15=1.;
  a20=casadi_sq(a03);
  a21=casadi_sq(a13);
  a20=(a20+a21);
  a21=arg[5]? arg[5][0] : 0;
  a22=casadi_sq(a21);
  a22=(a20+a22);
  a12=casadi_sq(a12);
  a07=(a07*a08);
  a06=(a06*a11);
  a07=(a07-a06);
  a07=(a08-a07);
  a06=casadi_sq(a07);
  a12=(a12-a06);
  a22=(a22-a12);
  a12=(a09*a21);
  a20=sqrt(a20);
  a06=(a12*a20);
  a22=(a22/a06);
  a23=casadi_fmin(a22,a15);
  a24=casadi_fmax(a23,a17);
  a24=casadi_sq(a24);
  a24=(a15-a24);
  a24=sqrt(a24);
  a24=(a17/a24);
  a25=(a17<=a23);
  a23=(a23<=a17);
  a23=(a25+a23);
  a25=(a25/a23);
  a23=(a22<=a15);
  a26=(a15<=a22);
  a26=(a23+a26);
  a23=(a23/a26);
  a03=(a03+a03);
  a19=(a03*a19);
  a13=(a13+a13);
  a16=(a13*a16);
  a19=(a19+a16);
  a16=(a19/a06);
  a22=(a22/a06);
  a20=(a20+a20);
  a19=(a19/a20);
  a19=(a12*a19);
  a19=(a22*a19);
  a16=(a16-a19);
  a16=(a23*a16);
  a16=(a25*a16);
  a16=(a24*a16);
  a18=(a18+a16);
  if (res[0]!=0) res[0][0]=a18;
  a18=cos(a00);
  a16=(a18*a02);
  a19=sin(a00);
  a26=sin(a05);
  a27=(a19*a26);
  a27=(a27*a08);
  a16=(a16-a27);
  a27=cos(a05);
  a28=(a19*a27);
  a28=(a28*a11);
  a16=(a16+a28);
  a28=casadi_sq(a16);
  a29=arg[4]? arg[4][0] : 0;
  a30=(a18*a27);
  a30=(a30*a11);
  a31=(a19*a02);
  a32=(a18*a26);
  a32=(a32*a08);
  a31=(a31+a32);
  a30=(a30-a31);
  a30=(a29-a30);
  a31=casadi_sq(a30);
  a28=(a28+a31);
  a31=(a16/a28);
  a32=sin(a00);
  a33=(a27*a32);
  a33=(a11*a33);
  a00=cos(a00);
  a34=(a02*a00);
  a35=(a26*a32);
  a35=(a08*a35);
  a34=(a34-a35);
  a33=(a33+a34);
  a34=(a31*a33);
  a28=(a30/a28);
  a35=(a27*a00);
  a35=(a11*a35);
  a02=(a02*a32);
  a00=(a26*a00);
  a00=(a08*a00);
  a02=(a02+a00);
  a35=(a35-a02);
  a02=(a28*a35);
  a34=(a34-a02);
  a02=casadi_sq(a16);
  a00=casadi_sq(a30);
  a02=(a02+a00);
  a00=casadi_sq(a21);
  a00=(a02+a00);
  a29=casadi_sq(a29);
  a27=(a27*a08);
  a26=(a26*a11);
  a27=(a27+a26);
  a27=(a27-a08);
  a26=casadi_sq(a27);
  a29=(a29-a26);
  a00=(a00-a29);
  a09=(a09*a21);
  a02=sqrt(a02);
  a21=(a09*a02);
  a00=(a00/a21);
  a29=casadi_fmin(a00,a15);
  a26=casadi_fmax(a29,a17);
  a26=casadi_sq(a26);
  a26=(a15-a26);
  a26=sqrt(a26);
  a26=(a17/a26);
  a32=(a17<=a29);
  a29=(a29<=a17);
  a29=(a32+a29);
  a32=(a32/a29);
  a29=(a00<=a15);
  a15=(a15<=a00);
  a15=(a29+a15);
  a29=(a29/a15);
  a16=(a16+a16);
  a35=(a16*a35);
  a30=(a30+a30);
  a33=(a30*a33);
  a35=(a35+a33);
  a33=(a35/a21);
  a00=(a00/a21);
  a02=(a02+a02);
  a35=(a35/a02);
  a35=(a09*a35);
  a35=(a00*a35);
  a33=(a33-a35);
  a33=(a29*a33);
  a33=(a32*a33);
  a33=(a26*a33);
  a34=(a34+a33);
  if (res[0]!=0) res[0][1]=a34;
  a34=cos(a05);
  a33=(a04*a34);
  a33=(a08*a33);
  a35=sin(a05);
  a04=(a04*a35);
  a04=(a11*a04);
  a33=(a33-a04);
  a03=(a03*a33);
  a04=(a01*a34);
  a04=(a08*a04);
  a01=(a01*a35);
  a01=(a11*a01);
  a04=(a04-a01);
  a13=(a13*a04);
  a03=(a03-a13);
  a07=(a07+a07);
  a35=(a08*a35);
  a34=(a11*a34);
  a35=(a35+a34);
  a07=(a07*a35);
  a07=(a03+a07);
  a07=(a07/a06);
  a03=(a03/a20);
  a12=(a12*a03);
  a22=(a22*a12);
  a07=(a07-a22);
  a23=(a23*a07);
  a25=(a25*a23);
  a24=(a24*a25);
  a10=(a10*a33);
  a14=(a14*a04);
  a10=(a10+a14);
  a24=(a24-a10);
  if (res[0]!=0) res[0][2]=a24;
  a24=cos(a05);
  a10=(a19*a24);
  a10=(a08*a10);
  a05=sin(a05);
  a19=(a19*a05);
  a19=(a11*a19);
  a10=(a10+a19);
  a28=(a28*a10);
  a19=(a18*a05);
  a19=(a11*a19);
  a18=(a18*a24);
  a18=(a08*a18);
  a19=(a19+a18);
  a31=(a31*a19);
  a28=(a28+a31);
  a30=(a30*a19);
  a16=(a16*a10);
  a30=(a30-a16);
  a27=(a27+a27);
  a11=(a11*a24);
  a08=(a08*a05);
  a11=(a11-a08);
  a27=(a27*a11);
  a27=(a30+a27);
  a27=(a27/a21);
  a30=(a30/a02);
  a09=(a09*a30);
  a00=(a00*a09);
  a27=(a27-a00);
  a29=(a29*a27);
  a32=(a32*a29);
  a26=(a26*a32);
  a28=(a28+a26);
  if (res[0]!=0) res[0][3]=a28;
  return 0;
}

CASADI_SYMBOL_EXPORT int ankle_jacobian(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ankle_jacobian_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ankle_jacobian_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ankle_jacobian_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ankle_jacobian_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ankle_jacobian_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ankle_jacobian_incref(void) {
}

CASADI_SYMBOL_EXPORT void ankle_jacobian_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ankle_jacobian_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int ankle_jacobian_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ankle_jacobian_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ankle_jacobian_name_in(casadi_int i) {
  switch (i) {
    case 0: return "pitch";
    case 1: return "roll";
    case 2: return "D";
    case 3: return "h1";
    case 4: return "h2";
    case 5: return "r";
    case 6: return "u_x";
    case 7: return "u_z";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ankle_jacobian_name_out(casadi_int i) {
  switch (i) {
    case 0: return "J";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ankle_jacobian_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ankle_jacobian_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ankle_jacobian_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ankle_jacobian_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
