/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ankle_functions_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {1, 1, 1};
static const casadi_int casadi_s1[3] = {2, 2, 1};

/* ankle_inv:(pitch,roll)->(phi_l,phi_r) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13;
  a00=-1.2000000000000000e-01;
  a01=arg[0]? arg[0][0] : 0;
  a02=cos(a01);
  a03=(a00*a02);
  a04=5.9999999999999998e-02;
  a05=sin(a01);
  a06=arg[1]? arg[1][0] : 0;
  a07=sin(a06);
  a08=(a05*a07);
  a08=(a04*a08);
  a03=(a03+a08);
  a08=(-a03);
  a09=4.8999999999999999e-01;
  a02=(a02*a07);
  a02=(a04*a02);
  a05=(a00*a05);
  a02=(a02-a05);
  a09=(a09-a02);
  a08=atan2(a08,a09);
  a03=casadi_sq(a03);
  a09=casadi_sq(a09);
  a03=(a03+a09);
  a09=1.4400000000000000e-02;
  a02=(a03+a09);
  a05=2.4009999999999998e-01;
  a07=cos(a06);
  a07=(a04*a07);
  a04=(a04-a07);
  a04=casadi_sq(a04);
  a05=(a05-a04);
  a02=(a02-a05);
  a05=2.3999999999999999e-01;
  a03=sqrt(a03);
  a03=(a05*a03);
  a02=(a02/a03);
  a03=1.;
  a02=casadi_fmin(a02,a03);
  a04=-1.;
  a02=casadi_fmax(a02,a04);
  a02=acos(a02);
  a08=(a08+a02);
  a02=1.5707963267948966e+00;
  a08=(a08-a02);
  if (res[0]!=0) res[0][0]=a08;
  a08=cos(a01);
  a07=(a00*a08);
  a10=-5.9999999999999998e-02;
  a01=sin(a01);
  a11=sin(a06);
  a12=(a01*a11);
  a12=(a10*a12);
  a07=(a07+a12);
  a12=(-a07);
  a13=3.7000000000000000e-01;
  a08=(a08*a11);
  a08=(a10*a08);
  a00=(a00*a01);
  a08=(a08-a00);
  a13=(a13-a08);
  a12=atan2(a12,a13);
  a07=casadi_sq(a07);
  a13=casadi_sq(a13);
  a07=(a07+a13);
  a09=(a07+a09);
  a13=1.3689999999999999e-01;
  a06=cos(a06);
  a06=(a10*a06);
  a10=(a10-a06);
  a10=casadi_sq(a10);
  a13=(a13-a10);
  a09=(a09-a13);
  a07=sqrt(a07);
  a05=(a05*a07);
  a09=(a09/a05);
  a09=casadi_fmin(a09,a03);
  a09=casadi_fmax(a09,a04);
  a09=acos(a09);
  a12=(a12+a09);
  a12=(a12-a02);
  if (res[1]!=0) res[1][0]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int ankle_inv(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ankle_inv_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ankle_inv_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ankle_inv_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ankle_inv_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ankle_inv_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ankle_inv_incref(void) {
}

CASADI_SYMBOL_EXPORT void ankle_inv_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ankle_inv_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int ankle_inv_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real ankle_inv_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ankle_inv_name_in(casadi_int i) {
  switch (i) {
    case 0: return "pitch";
    case 1: return "roll";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ankle_inv_name_out(casadi_int i) {
  switch (i) {
    case 0: return "phi_l";
    case 1: return "phi_r";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ankle_inv_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ankle_inv_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ankle_inv_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ankle_inv_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* ankle_jacobian:(pitch,roll)->(J[2x2]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34;
  a00=-1.2000000000000000e-01;
  a01=arg[0]? arg[0][0] : 0;
  a02=cos(a01);
  a03=(a00*a02);
  a04=5.9999999999999998e-02;
  a05=sin(a01);
  a06=arg[1]? arg[1][0] : 0;
  a07=sin(a06);
  a08=(a05*a07);
  a08=(a04*a08);
  a03=(a03+a08);
  a08=casadi_sq(a03);
  a09=4.8999999999999999e-01;
  a10=(a02*a07);
  a10=(a04*a10);
  a11=(a00*a05);
  a10=(a10-a11);
  a09=(a09-a10);
  a10=casadi_sq(a09);
  a08=(a08+a10);
  a10=(a03/a08);
  a11=sin(a01);
  a12=(a07*a11);
  a12=(a04*a12);
  a13=cos(a01);
  a14=(a00*a13);
  a12=(a12+a14);
  a14=(a10*a12);
  a08=(a09/a08);
  a07=(a07*a13);
  a07=(a04*a07);
  a11=(a00*a11);
  a07=(a07-a11);
  a11=(a08*a07);
  a14=(a14-a11);
  a11=-1.;
  a13=1.;
  a15=casadi_sq(a03);
  a16=casadi_sq(a09);
  a15=(a15+a16);
  a16=1.4400000000000000e-02;
  a17=(a15+a16);
  a18=2.4009999999999998e-01;
  a19=cos(a06);
  a19=(a04*a19);
  a19=(a04-a19);
  a20=casadi_sq(a19);
  a18=(a18-a20);
  a17=(a17-a18);
  a18=2.3999999999999999e-01;
  a15=sqrt(a15);
  a20=(a18*a15);
  a17=(a17/a20);
  a21=casadi_fmin(a17,a13);
  a22=casadi_fmax(a21,a11);
  a22=casadi_sq(a22);
  a22=(a13-a22);
  a22=sqrt(a22);
  a22=(a11/a22);
  a23=(a11<=a21);
  a21=(a21<=a11);
  a21=(a23+a21);
  a23=(a23/a21);
  a21=(a17<=a13);
  a24=(a13<=a17);
  a24=(a21+a24);
  a21=(a21/a24);
  a03=(a03+a03);
  a07=(a03*a07);
  a09=(a09+a09);
  a12=(a09*a12);
  a07=(a07+a12);
  a12=(a07/a20);
  a17=(a17/a20);
  a15=(a15+a15);
  a07=(a07/a15);
  a07=(a18*a07);
  a07=(a17*a07);
  a12=(a12-a07);
  a12=(a21*a12);
  a12=(a23*a12);
  a12=(a22*a12);
  a14=(a14+a12);
  if (res[0]!=0) res[0][0]=a14;
  a14=cos(a01);
  a12=(a00*a14);
  a07=-5.9999999999999998e-02;
  a24=sin(a01);
  a25=sin(a06);
  a26=(a24*a25);
  a26=(a07*a26);
  a12=(a12+a26);
  a26=casadi_sq(a12);
  a27=3.7000000000000000e-01;
  a28=(a14*a25);
  a28=(a07*a28);
  a29=(a00*a24);
  a28=(a28-a29);
  a27=(a27-a28);
  a28=casadi_sq(a27);
  a26=(a26+a28);
  a28=(a12/a26);
  a29=sin(a01);
  a30=(a25*a29);
  a30=(a07*a30);
  a01=cos(a01);
  a31=(a00*a01);
  a30=(a30+a31);
  a31=(a28*a30);
  a26=(a27/a26);
  a25=(a25*a01);
  a25=(a07*a25);
  a00=(a00*a29);
  a25=(a25-a00);
  a00=(a26*a25);
  a31=(a31-a00);
  a00=casadi_sq(a12);
  a29=casadi_sq(a27);
  a00=(a00+a29);
  a16=(a00+a16);
  a29=1.3689999999999999e-01;
  a01=cos(a06);
  a01=(a07*a01);
  a01=(a07-a01);
  a32=casadi_sq(a01);
  a29=(a29-a32);
  a16=(a16-a29);
  a00=sqrt(a00);
  a29=(a18*a00);
  a16=(a16/a29);
  a32=casadi_fmin(a16,a13);
  a33=casadi_fmax(a32,a11);
  a33=casadi_sq(a33);
  a33=(a13-a33);
  a33=sqrt(a33);
  a33=(a11/a33);
  a34=(a11<=a32);
  a32=(a32<=a11);
  a32=(a34+a32);
  a34=(a34/a32);
  a32=(a16<=a13);
  a13=(a13<=a16);
  a13=(a32+a13);
  a32=(a32/a13);
  a12=(a12+a12);
  a25=(a12*a25);
  a27=(a27+a27);
  a30=(a27*a30);
  a25=(a25+a30);
  a30=(a25/a29);
  a16=(a16/a29);
  a00=(a00+a00);
  a25=(a25/a00);
  a25=(a18*a25);
  a25=(a16*a25);
  a30=(a30-a25);
  a30=(a32*a30);
  a30=(a34*a30);
  a30=(a33*a30);
  a31=(a31+a30);
  if (res[0]!=0) res[0][1]=a31;
  a31=cos(a06);
  a05=(a05*a31);
  a05=(a04*a05);
  a03=(a03*a05);
  a02=(a02*a31);
  a02=(a04*a02);
  a09=(a09*a02);
  a03=(a03-a09);
  a19=(a19+a19);
  a09=sin(a06);
  a04=(a04*a09);
  a19=(a19*a04);
  a19=(a03+a19);
  a19=(a19/a20);
  a03=(a03/a15);
  a03=(a18*a03);
  a17=(a17*a03);
  a19=(a19-a17);
  a21=(a21*a19);
  a23=(a23*a21);
  a22=(a22*a23);
  a08=(a08*a05);
  a10=(a10*a02);
  a08=(a08+a10);
  a22=(a22-a08);
  if (res[0]!=0) res[0][2]=a22;
  a22=cos(a06);
  a24=(a24*a22);
  a24=(a07*a24);
  a12=(a12*a24);
  a14=(a14*a22);
  a14=(a07*a14);
  a27=(a27*a14);
  a12=(a12-a27);
  a01=(a01+a01);
  a06=sin(a06);
  a07=(a07*a06);
  a01=(a01*a07);
  a01=(a12+a01);
  a01=(a01/a29);
  a12=(a12/a00);
  a18=(a18*a12);
  a16=(a16*a18);
  a01=(a01-a16);
  a32=(a32*a01);
  a34=(a34*a32);
  a33=(a33*a34);
  a26=(a26*a24);
  a28=(a28*a14);
  a26=(a26+a28);
  a33=(a33-a26);
  if (res[0]!=0) res[0][3]=a33;
  return 0;
}

CASADI_SYMBOL_EXPORT int ankle_jacobian(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ankle_jacobian_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ankle_jacobian_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ankle_jacobian_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ankle_jacobian_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ankle_jacobian_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ankle_jacobian_incref(void) {
}

CASADI_SYMBOL_EXPORT void ankle_jacobian_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ankle_jacobian_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int ankle_jacobian_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ankle_jacobian_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ankle_jacobian_name_in(casadi_int i) {
  switch (i) {
    case 0: return "pitch";
    case 1: return "roll";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ankle_jacobian_name_out(casadi_int i) {
  switch (i) {
    case 0: return "J";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ankle_jacobian_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ankle_jacobian_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ankle_jacobian_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ankle_jacobian_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
